[project]
name = "word2vec-demo"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "datasets>=4.0.0",
    "gensim>=4.3.3",
    "ipykernel>=6.30.1",
    "pandas>=2.3.2",
    "pre-commit>=4.3.0",
    "spacy>=3.8.7",
]
